"""add duration_hours

Revision ID: 51c2dc6532f6
Revises: dd1f10aa1b94
Create Date: 2025-12-22 14:51:00.588249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51c2dc6532f6'
down_revision: Union[str, Sequence[str], None] = 'dd1f10aa1b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_bookings')
    op.drop_table('movement_notifications')
    op.drop_index(op.f('ix_payroll_id'), table_name='payroll')
    op.drop_table('payroll')
    op.drop_index(op.f('ix_red_zones_id'), table_name='red_zones')
    op.drop_table('red_zones')
    op.drop_table('shift_templates')
    op.drop_index(op.f('ix_daily_distance_id'), table_name='daily_distance')
    op.drop_table('daily_distance')
    op.drop_index(op.f('ix_gps_locations_id'), table_name='gps_locations')
    op.drop_table('gps_locations')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_column('users', 'hourly_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('shifts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hours_worked', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payout', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('shifts_rider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shifts_pkey'))
    )
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('gps_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('gps_locations_rider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gps_locations_pkey'))
    )
    op.create_index(op.f('ix_gps_locations_id'), 'gps_locations', ['id'], unique=False)
    op.create_table('daily_distance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('daily_distance_rider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_distance_pkey')),
    sa.UniqueConstraint('rider_id', 'date', name=op.f('uq_rider_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_daily_distance_id'), 'daily_distance', ['id'], unique=False)
    op.create_table('shift_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shift_templates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('red_zones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('radius_meters', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('red_zones_pkey'))
    )
    op.create_index(op.f('ix_red_zones_id'), 'red_zones', ['id'], unique=False)
    op.create_table('payroll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('payroll_rider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payroll_pkey'))
    )
    op.create_index(op.f('ix_payroll_id'), 'payroll', ['id'], unique=False)
    op.create_table('movement_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('minutes_stopped', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('movement_notifications_rider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('movement_notifications_pkey'))
    )
    op.create_table('shift_bookings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shift_template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('shift_bookings_rider_id_fkey')),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], name=op.f('shift_bookings_shift_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_bookings_pkey'))
    )
    # ### end Alembic commands ###
