"""add job_type to users

Revision ID: 7b992c539189
Revises: d8b85561cf18
Create Date: 2025-12-21 02:45:57.584550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b992c539189'
down_revision: Union[str, Sequence[str], None] = 'd8b85561cf18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_type', sa.String(), server_default='fulltime', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_type')
    # ### end Alembic commands ###
